### PR TITLE
Add tutorial for awkward arrays

### PR DESCRIPTION
**Pull request by grst**

### CODE REVIEW

**Comment by grst** [comment]
Hi @ivirshup, 

I now added an example to store ragged ids of transcript ids in `adata.varm`. 
Do you have anything else in mind that you would want me to show in the tutorial?

**Comment by ivirshup** [comment]
I think that's good. Pretty close to what I was thinking [(exon positions for "canonical transcript")](https://gist.github.com/ivirshup/9cb994e473f9f6f1325a361195d4d7a6).

**Review by ivirshup — COMMENTED** [review]
Could you put the imports under the title and author?

image

**Comment by grst** [comment]
done. I also put the warning on the top. 

image

**Review by ivirshup — APPROVED** [review]
Great, thanks!

**Pull request merged**
